    - name: Zip published app
      run: |
        cd publish
        zip -r ../SailDisplay.zip .

    - name: Upload ZIP to GitHub Releases
      uses: softprops/action-gh-release@v2
      with:
        tag_name: latest
        files: SailDisplay.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
